### ISSUE TITLE
 prueba extra en el modulo de pacientes

### ISSUE THREAD

**Issue by GhostIMA** [DemianEros/VitaSmart-CAIM#81]
prueba extra en el modulo de pacientes al momento de dar click izquierdo en el botón de cancelar se muestra esta ventana emergente con una mala redacion porque no es cita tendría que decir cancelar la edición del paciente 
![image](https://github.com/user-attachments/assets/f5ddabf0-bcfd-4bc4-9f28-7278ae13b473)

**Comment by GhostIMA** [comment]
pagina 55 manual de usuario para correcion de imagen

**Comment by BetoPlox99** [comment]
Fixed
